name: 'Build Binaries'
description: 'Build executables for script'

runs:
  using: 'composite'
  steps:
    - name: Transpile
      run: npm run transpile
      shell: bash

    - name: Compile
      run: npm run compile
      shell: bash

    - name: List Files
      run: ls -xl ./dist
      shell: bash
