name: 'Setup'
description: 'Build executables for script'
inputs:
  node-version:
    description: 'Version of node to use'
    required: false
    default: 18
  access-token:
    description: 'NPM access token for login'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node_version }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci
      shell: bash

    - name: NPM Login
      if: ${{ inputs.access-token != '' }}
      run: |
        npm config set //registry.npmjs.org/:_authToken=${{ inputs.access-token }}
        npm whoami
      shell: bash
