name: Create Release
on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pull-requests: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-deps
        with:
          access-token: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Testing
        uses: ./.github/actions/testing

      - name: Build Executables
        uses: ./.github/actions/build-binaries

      - name: Create New Version
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-tag: 'true'
          skip-commit: 'true'
          skip-push: true
          commit-message: 'version bump for new release'
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: See Version
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new version $NEW_TAG"

      - name: NPM Version Bump
        run: npm version ${{ steps.version-bump.outputs.newTag }} --allow-same-version

      - name: See Config
        run: cat ./package.json

      - name: Push Changes
        run: |
          git status
          git push -u origin

      - name: Create GitHub Release
        run: |
          tar -zcvf dist.tar.gz ./dist
          gh release create ${{ steps.version-bump.outputs.newTag }} ./dist.tar.gz --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Publish Package
        run: npm publish
