name: Create Release
on:
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-deps
        with:
          access-token: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Install ldid
        uses: MOZGIII/install-ldid-action@v1
        with:
          tag: v2.1.5-procursus7

      - name: Transpile and Compile
        uses: ./.github/actions/build-binaries

      - name: Create GitHub Release
        run: |
          VERSION=$(cat package.json | jq -r '.version')
          echo $VERSION
          tar -zcvf dist.tar.gz ./dist
          gh release create $VERSION ./dist.tar.gz --generate-notes
        env:
          GH_TOKEN: ${{ github.token }}
