name: Unit Testing
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./actions/setup.yml

      - name: Unit Testing
        run: npm run test

  build-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./actions/setup.yml

      - name: Dry Build
        uses: ./actions/build-binaries.yml

      - name: List Files
        run: cat ./dist
