name: Unit Testing
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-deps

      - name: Unit Testing
        run: npm run test

  build-binaries:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Directory
        run: pwd

      - name: Setup
        uses: ./.github/actions/setup-deps
        with:
          access-token: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Dry Build
        uses: ./.github/actions/build-binaries
