name: Unit Testing
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-deps

      - name: Testing
        uses: ./.github/actions/testing

  dry-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-deps

      - name: Dry Build
        uses: ./.github/actions/build-binaries
